name: 🐘 Setup Gradle Managed Devices
description: Gradle Managed Devices setup
runs:
  using: composite
  steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: yes | sdkmanager --licenses || true

    - name: Setup GMD
      run: ./gradlew :benchmarks:pixel6Api33Setup
        --info
        -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
        -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
