name: 🐘 Setup Gradle
description: Gradle setup and wrapper validation
inputs:
  cache-encryption-key:
    description: Gradle Configuration Cache encryption key
    required: false
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: on-failure
        build-scan-publish: true
        build-scan-terms-of-use-agree: yes
        build-scan-terms-of-use-url: https://gradle.com/terms-of-service
        cache-cleanup: on-success
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        gradle-home-cache-strict-match: true
        validate-wrappers: true
