name: NightlyBaselineProfiles

on:
  workflow_dispatch:
  schedule:
    - cron:  '42 4 * * *'

jobs:
  baseline_profiles:
    name: "Generate Baseline Profiles"
    if: github.repository == 'android/nowinandroid'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kvm
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - uses: ./.github/actions/setup-gradle-properties
      - uses: ./.github/actions/setup-gradle-managed-devices

      - name: Build all build type and flavor permutations including baseline profiles
        run: ./gradlew :app:assemble
             -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=baselineprofile
             -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
             -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
